config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#new"

  get "archive" => "application#archive"
  get "create" => "application#create"
  get "edit" => "application#edit"
  get "logout" => "sessions#destroy"
  get "new" => "application#new"
  post "create" => "application#create"
  post "download" => "application#download"
  post "login" => "sessions#create"
  post "new" => "application#new"
  post "update" => "application#update"
end

app/controllers/application_controller.rb
# coding: utf-8
# frozen_string_literal: true

require "resque"

class ApplicationController < ActionController::Base
  include ApplicationHelper
  include SessionsHelper

  protect_from_forgery with: :exception

  def new
    @title = "Mint ARKs"

    return redirect_to root_url unless logged_in?

    # The DataCite element "Resource Type" has two parts: "general
    # type" has a controlled vocabulary while "specific type" can be
    # anything.  So we need to handle it in two separate form
    # elements: a <select> drop-down for the general type, and a text
    # field for the specific type.  Here we merge them together.
    merge_resourcetypes!(params)

    @profile = params[:profile].to_sym if params[:profile]
    # All objects, whether extracted from a spreadsheet or entered in
    # the form, are collected in this hash.  See README.md for an
    # overview of the data model.
    @objects = {}
    @objects[:new] = {}
    @objects[:updates] = {}

    if params[:spreadsheet]
      book = ExcelHelper.open(params[:spreadsheet])
      records = ExcelHelper.scrape(book, profile: @profile)

      @objects[:new] = records[:new]
      @objects[:updates] = records[:updates]

      #
      # Setting more instance variables for the views
      #
      @status = if @objects && @objects[:updates]&.all?(&:empty?)
                  :new
                else
                  :updates
                end

      profile_columns = case @profile
                        when :erc
                          ERC_ELEMENTS.map { |e| "erc_#{e}" }
                        when :dc
                          DC_ELEMENTS.map { |e| "dc_#{e}" }
                        when :datacite
                          DATACITE_ELEMENTS.map { |e| "datacite_#{e}" }
                        end

      @extra_columns = @objects[@status][@profile][0].keys.reject do |k|
        ::ApplicationHelper.standard_header? k
      end

      @all_columns = profile_columns +
                     %w[target ark id] +
                     @extra_columns

    # We enter this branch if the user provided object metadata
    # through the Mint-a-single-ARK form on the main page
    else
      return unless params[:new] && !params[:new][:erc].empty?

      # The Mint-a-single-ARK form can only yield one object, but
      # @objects[:erc] is always an array, so our object will be the
      # first one
      to_mint = params[:new][:erc]

      previously_minted = ApplicationHelper.duplicates(
        to_mint,
        Item.where.not(target: "")
      )

      if previously_minted.empty?
        @objects[:new][:erc] = to_mint
      else
        @objects[:updates][:erc] = previously_minted
      end
    end

    return if @objects[:updates].all?(&:empty?)

    # If there are duplicates, render edit.html.erb; otherwise render
    # the default new.html.erb
    flash.now[:warning] = "The objects listed have already been minted. " \
                          "You may update their metadata below."
  end

  def update
    return redirect_to root_url unless logged_in?
    return redirect_to root_url unless (profile = params[:profile].to_sym)

    merge_resourcetypes!(params)

    @objects = {}
    @objects[:new] = {}

    # Update the modified object with Ezid and in our database
    @objects[:updates] = {}
    @objects[:updates][profile] = params[:updates][profile]

    unless params[:new].nil?
      @objects[:new][profile] = params[:new][profile].reject do |record|
        @objects[:updates][profile].include?(record)
      end
    end

    render "new"
  end

  def create
    @title = "Success"

    return redirect_to root_url unless logged_in?
    return redirect_to root_url unless (profile = params[:profile].to_sym)

    merge_resourcetypes!(params)

    @objects = {}
    @objects[:new] = params[:new] || {}
    @objects[:updates] = params[:updates] || {}

    new_duplicates = ApplicationHelper.duplicates(
      @objects[:new][profile],
      Item.where.not(target: "")
    )

    unless new_duplicates.empty?
      # Populate the duplicates bucket
      @objects[:updates][profile] ||= []
      @objects[:updates][profile] += new_duplicates
      @objects[:updates][profile].flatten!

      # Remove duplicates from the :new bucket
      @objects[:new][profile].reject! do |record|
        @objects[:updates][profile].any? do |dup|
          (!record["ark"].nil? && dup["ark"] == record["ark"]) ||
            (record["target"] != "" && dup["target"] == record["target"])
        end
      end

      flash.now[:warning] = "The objects listed have already been minted. " \
                            "You may update their metadata below."
      return render "edit" unless new_duplicates.empty?
    end

    resque_args = {
      "email" => params[:email],
      "profile" => params[:profile],
      "user" => params[:user],
    }
    if params[:updates]
      resque_args["updates"] = params[:updates][params[:profile]]
    end

    resque_args["new"] = params[:new][params[:profile]] if params[:new]

    Resque.enqueue(EzidHelper::Minter, resque_args)
  end

  def archive
    return redirect_to root_url unless logged_in?
    @title = "Records minted by #{current_user}"

    @objects = {}
    @objects[:archive] = {}

    PROFILE_SYMBOLS.each do |profile|
      @objects[:archive][profile] = {}
    end

    # See http://www.postgresqltutorial.com/postgresql-array/ for
    # array syntax
    Item.where("? = any(created_by)", current_user)
      .order(:job_id)
      .reverse_order
      .each do |record|

      record = record.as_json
      profile = record["profile"].to_sym

      # Non-standard headers (such as Aleph system number) are
      # collected as a JSON object in the :nonstandard_headers field
      # of PostgreSQL; here we unpack that object and return them to
      # first-class elements of the record.
      record["nonstandard_headers"].each do |k, v|
        record[k.to_sym] = v
      end

      job_key = record["job_id"].to_sym
      @objects[:archive][profile][job_key] ||= []
      @objects[:archive][profile][job_key] << record
    end
  end

  def download
    return redirect_to root_url unless logged_in?
    return redirect_to new_path unless (profile = params[:profile].to_sym)

    records = if params[:job_id]
                fetch_records(
                  profile: profile,
                  job_id: params[:job_id]
                )
              else
                fetch_records(
                  profile: profile,
                  user: params[:user]
                )
              end

    columns = case profile
              when :datacite
                DATACITE_ELEMENTS.map { |e| "datacite.#{e}" }
              when :dc
                DC_ELEMENTS.map { |e| "dc.#{e}" }
              when :erc
                ERC_ELEMENTS.map { |e| "erc.#{e}" }
              end

    columns << "location"
    columns << "ARK"
    columns += records.first.keys.reject do |k|
      ::ApplicationHelper.standard_header? k
    end

    workbook = RubyXL::Workbook.new
    ExcelHelper.write_sheet(workbook, columns, records)

    begin
      temp = Rails.root.join("tmp", "#{params[:filename]}.xlsx")
      workbook.write(temp)

      # Sending the data in a File.open block ensures that it's all
      # sent before the tempfile is removed
      File.open(temp, "r") do |f|
        send_data(
          f.read,
          filename: File.basename(temp),
          type: "application/"\
                "vnd.openxmlformats-officedocument"\
                ".spreadsheetml.sheet"
        )
      end
    ensure
      FileUtils.rm_f temp
    end
  end
end

app/helpers/application_helper.rb
# coding: utf-8
# frozen_string_literal: true

# Application helper methods
module ApplicationHelper
  # Return the CANDIDATES that match (ARK or target/location) any in AGAINST.
  #
  # @param [Hash] candidate An Ezid-ready object hash
  # @param [ActiveRecord::Relation, Array<Hash>] against
  #
  # @return [Array<Hash>]
  def self.duplicates(candidates, against)
    matches = []
    return matches if candidates.nil?

    candidates.each_with_index do |candidate, i|
      next if candidate[:ark].blank?

      db_record = Item.find_by(ark: candidate[:ark])
      # If we have that ARK in our database, add the DB ID to the
      # object so the existing DB record gets updated, instead of
      # creating a new one
      matches[i] = if db_record
                     candidate.merge(id: db_record[:id])
                   else
                     candidate
                   end
    end

    against.each do |db_record|
      candidates.each_with_index do |candidate, i|
        # If a duplicate of this candidate was found above, while
        # checking against ARKs
        next unless matches[i].nil?

        next unless candidate[:target]
        next unless candidate[:target] == db_record[:target]

        matches[i] = candidate.merge(id: db_record[:id], ark: db_record[:ark])
      end
    end
    matches
  end

  # The DataCite element "Resource Type" has two parts: "general type"
  # has a controlled vocabulary while "specific type" can be anything.
  # So we need to handle it in two separate form elements: a <select>
  # drop-down for the general type, and a text field for the specific
  # type.  This method merges them together.
  #
  # @param [ActionController::Parameters] params
  def merge_resourcetypes!(params)
    return unless (params[:new] && params[:new][:datacite]) ||
                  (params[:updates] && params[:updates][:datacite])

    # puts "Before: #{params.inspect}"

    [:new, :updates].each do |status|
      next unless params[status]

      params[status][:datacite].each_with_index do |param, i|
        next unless param[:datacite_resourcetype]

        params[status][:datacite][i][:datacite_resourcetype] +=
          "/#{param[:datacite_resourcesubtype]}"

        params[status][:datacite][i].delete :datacite_resourcesubtype
      end
    end

    # puts "After: #{params.inspect}"
  end

  # "Standard headers" include the elements of each metadata profile,
  # as well as defined column headers like ARK, location/target,
  # creation metadata, and other information.  Non-standard headers
  # are allowed but need special handling.
  #
  # @param [Symbol, String] header
  def self.standard_header?(header)
    CONTROLLED_HEADERS.include?(header.to_s
                                 .sub(/^erc_/, "")
                                 .sub(/^datacite_/, "")
                                 .sub(/^dc_/, ""))
  end

  def self.ezid_header?(header)
    EZID_HEADERS.include?(header.to_s
                           .sub(/^erc_/, "")
                           .sub(/^datacite_/, "")
                           .sub(/^dc_/, ""))
  end

  # Safari's JavaScript performance is noticably worse than other
  # browsers when rendering the interactive tables, due to the large
  # number of event listeners being processed.  So we issue a warning
  # for users about using Safari for large batches.
  def safari?
    request.env["HTTP_USER_AGENT"] &&
      request.env["HTTP_USER_AGENT"][/(Safari)/] &&
      !request.env["HTTP_USER_AGENT"][/(Chrome)/]
  end

  # Retrieve records from the DB and format them in a hash suitable
  # for writing to a spreadsheet with RubyXL.
  #
  # @param [Hash] options
  #
  # @option options [Symbol] :profile
  # @option options [String] :job_id
  # @option options [String] :user The user who ran the original
  #   job(s), corresponding to the `created_by` column in the database
  #
  # @return [Hash]
  def fetch_records(options = {})
    profile = options.fetch(:profile)
    query = if (job_id = options.fetch(:job_id, nil))
              { job_id: job_id }
            else
              [
                "? = any(created_by) AND profile = ?",
                options.fetch(:user),
                profile,
              ]
            end

    Item.where(query).map do |record|
      columns = case profile
                when :datacite
                  {
                    datacite_title: record[:datacite_title],
                    datacite_creator: record[:datacite_creator],
                    datacite_resourcetype: record[:datacite_resourcetype],
                    datacite_publicationyear: record[:datacite_publicationyear],
                    datacite_publisher: record[:datacite_publisher],
                    target: record[:target],
                    ark: record[:ark],
                  }
                when :dc
                  {
                    dc_title: record[:dc_title],
                    dc_creator: record[:dc_creator],
                    dc_type: record[:dc_type],
                    dc_date: record[:dc_date],
                    dc_publisher: record[:dc_publisher],
                    target: record[:target],
                    ark: record[:ark],
                  }
                when :erc
                  {
                    erc_what: record[:erc_what],
                    erc_who: record[:erc_who],
                    erc_when: record[:erc_when],
                    target: record[:target],
                    ark: record[:ark],
                  }
                end
      record["nonstandard_headers"].each do |k, v|
        columns[k.to_sym] = v
      end
      columns
    end
  end
end

app/views/application/_table.html.erb
<table id='<%= @status %>' class='<%= @profile %> text'>
  <thead><tr>
    <% case @profile %>
    <% when :erc %>
      <th class='standard_header'></th>
      <th class='standard_header'>What</th>
      <th class='standard_header'>Who</th>
      <th class='standard_header'>When</th>
      <th class='standard_header'>Location</th>
      <th class='standard_header'>ARK</th>
      <th class='standard_header id'></th>
    <% when :dc %>
      <th class='standard_header'></th>
      <th class='standard_header'>Title</th>
      <th class='standard_header'>Creator</th>
      <th class='standard_header'>Type</th>
      <th class='standard_header'>Date</th>
      <th class='standard_header'>Publisher</th>
      <th class='standard_header'>Location</th>
      <th class='standard_header'>ARK</th>
      <th class='standard_header id'></th>
    <% when :datacite %>
      <th class='standard_header'></th>
      <th class='standard_header'>Title</th>
      <th class='standard_header'>Creator</th>
      <th class='standard_header'colspan='2'>Resource Type</th>
      <th class='standard_header'>Publication Year</th>
      <th class='standard_header'>Publisher</th>
      <th class='standard_header'>Location</th>
      <th class='standard_header'>ARK</th>
      <th class='standard_header id'></th>
    <% end %>

    <%
    # Spaces aren't allowed in CSS classes, but we want to avoid
    # collisions if for some reason a user has columns "cat stuff" and
    # "catstuff"; therefore replace spaces with an uncommon Unicode
    # character
    %>
    <% @extra_columns.each do |k| %>
      <th class='<%= k.to_s.tr(" ", "〰") %>'><%= k %></th>
    <% end %>

  </tr></thead>
  <tbody>

    <% @objects[@status][@profile].reject(&:empty?).each do |row| %>

    <tr>
      <% # Add empty cell for displaying row numbers %>
      <td class="line_number"></td>

      <% @all_columns.each do |e| %>
        <%
        # Hashes created by {ExcelHelper.scrape} have
        # symbols as keys, while hashes from pg (PostgreSQL gem) use
        # strings (because we run the Item objects through as_json to
        # make them usable).  So we need to convert the element to a
        # symbol in order to access the former values, but NOT when we
        # want to access the latter values (trying to access pg hashes
        # using symbols returns empty strings instead of the hash's
        # value).
        e = e.to_sym unless (row[e.to_sym]).to_s == ""
        %>

        <%
        # The value of the metadata type (e.g., ARK, ResourceType, title)
        #
        # may be "ark:/99999/fk4f76kg6t", "Image", "Harry Potter and
        # the Philosopher's Stone", etc.
        value = row[e]
        %>

        <% if e.to_s == "datacite_resourcetype" %>
          <%
          # split resourcetype into general and specific types; merged
          # with {ApplicationHelper.merge_resourcetypes!}
          general, value = if value.nil?
                             ["", ""]
                           else
                             row[e].downcase.split("/")
                           end
          %>

          <td class='<%= e %>'>
            <select name='<%= @status %>[<%= @profile %>][][<%= e %>]'>"
              <% RESOURCE_TYPES_GENERAL.each do |t| %>
                <option value='<%= t %>' <%= "selected" if t.casecmp(general).zero? %>>
                  <%= t %>
                </option>
              <% end %>
            </select>
          </td>

          <%
          # The general type must be one of RESOURCE_TYPES_GENERAL,
          # but the specific type can be anything, so we need two
          # inputs that are glued together with
          # {ApplicationHelper.merge_resourcetypes!} before submitting
          # to Ezid
          # http://ezid.cdlib.org/doc/apidoc.html#profile-datacite
          e = :datacite_resourcesubtype
          %>
        <% end %>

        <td>

          <% if e.to_s == "ark" %>
            <% if value.blank? %>
              <span class='ark'></span>
            <% else %>
              <a class='ark' href='http://ezid.cdlib.org/id/<%= value %>'><%= value %></a>
            <% end %>
          <% end %>

          <% always_hide = e.to_s == "ark" || e.to_s == "id" %>

          <% input_type = if always_hide
                            "hidden"
                          elsif e.to_s == "target"
                            "url"
                          else
                            "text"
                          end
          %>

          <input class='<%= e.to_s.tr(" ", "〰") %>'
            type='<%= input_type %>'
            name='<%= @status %>[<%= @profile %>][][<%= e %>]'

            <%=
            # FIXME: `required` doesn't work on Safari:
            # https://bugs.webkit.org/show_bug.cgi?id=28649
            # https://bugs.webkit.org/show_bug.cgi?id=40520
            " required " if e == :erc_what || e == :dc_title || e == :datacite_title %>

            value="<%= html_escape(value) %>"

            <% placeholder = if e == :datacite_resourcesubtype
                               "/ specific type"
                             elsif e.to_s != "target"
                               "Give me a value!"
                             else
                               ""
                             end
            %>

            placeholder='<%= placeholder %>'>
        </td>
      <% end %>

      <td class='delete'><%= button_tag "✘", type: "button", class: "delete" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if @status == :new %>
  <%= button_tag("Add row", :type => "button", :class => "add #{@profile}") %>
<% end %>

app/views/application/_upload.html.erb
<header>
  <h1>Upload or input metadata</h1>
</header>

<h2>Upload Excel spreadsheet</h2>
<%= form_tag({:controller => "application", :action => "new"}, :multipart => true) do %>
<%=
safe_join(
  [
    label_tag(:spreadsheet),
    file_field_tag(:spreadsheet, :required => true),

    radio_button_tag(:profile, "dc"),
    label_tag(:profile_dc, "DublinCore"),
    radio_button_tag(:profile, "datacite"),
    label_tag(:profile_datacite, "DataCite"),
    radio_button_tag(:profile, "erc", :active => true),
    label_tag(:profile_erc, "ERC"),

    submit_tag("Upload"),
  ]
)
%>
<% end %>

<h2>Mint a single ARK</h2>
<%= form_tag({:controller => "application", :action => "new"}) do %>
<%
  inputs = {
    :erc_what => "What",
    :erc_who => "Who",
    :erc_when => "When",
    :target => "Location (URL)",
  }
%>
  <% inputs.each do |k, v| %>
    <label for='<%= k %>'><%= v %></label>
    <input id='<%= k %>' <%= 'required' if k == :erc_what %> type='text' name='new[erc][][<%= k %>]'></input>
  <% end %>

  <input type='hidden' name='profile' value='erc'>
  <%= submit_tag("Mint") %>
<% end %>

app/views/application/archive.html.erb
<header>
  <h1>Records minted by Active Directory user "<%= current_user %>" (<a href='<%= new_path %>' title='Mint ARKs'>mint more</a>)</h1>
</header>

<p>Minted ARKs from jobs that are in progress may appear on this page;
wait until you receive an email confirming that all records have been
processed before downloading the job.</p>

<% PROFILE_SYMBOLS.each do |sym|
  next if @objects[:archive][sym].empty? %>

  <% if sym == :datacite %>
    <h2>DataCite</h2>

    <%= form_tag(:controller => "application", :action => "download") do %>
      <input type='hidden' name='profile' value='datacite'>
      <input type='hidden' name='user' value='<%= current_user %>'>
      <input type='hidden' name='filename' value='datacite_ALL_<%= Time.now.strftime('%F_%H.%M.%S') %>'>
      <%= submit_tag("Download all DataCite records") %>
    <% end %>

    <% @objects[:archive][:datacite].each_value do |job| %>
      <%= form_tag(:controller => "application", :action => "download") do %>
        <% time = Time.at(job.first["job_id"].sub(/.*_([0-9]*)/, '\1').to_i) %>

        <input type='hidden' name='profile' value='datacite'>
        <input type='hidden' name='job_id' value='<%= job.first['job_id'] %>'>
        <input type='hidden' name='filename' value='datacite_<%= time.strftime('%F_%H.%M.%S') %>'>
        <h3>Job: <%= time.strftime('%F at %R') %></h3>
        <%= submit_tag("Download this job") %>
      <% end %>

      <table class='minted'><thead><tr>
        <th></th><th>Title</th><th>Creator</th>
        <th>Resource Type</th><th>Publication Year</th>
        <th>Publisher</th><th>Location</th><th>ARK</th>

        <% job.first.keys.reject { |k| ApplicationHelper.standard_header? k }.each do |k| %>
          <th><%= k %></th>
        <% end %>

      </tr>
      </thead>
      <tbody>

        <% job.sort_by { |r| r["ark"] }.each do |rec| %>
          <tr>
            <td class='line_number'></td>
            <td><%= rec["datacite_title"] %></td>
            <td><%= rec["datacite_creator"] %></td>
            <td><%= rec["datacite_resourcetype"] %></td>
            <td><%= rec["datacite_publicationyear"] %></td>
            <td><%= rec["datacite_publisher"] %></td>
            <% if !rec["target"].nil? && rec["target"].start_with?("http") %>
              <td><a href="<%= rec["target"] %>"><%= rec["target"] %></a></td>
            <% else %>
              <td><%= rec["target"] %></td>
            <% end %>
            <td><a href="http://ezid.cdlib.org/id/<%= rec["ark"] %>"><%= rec["ark"] %></a></td>

            <% rec.keys.reject { |k| ApplicationHelper.standard_header? k }.each do |k| %>
              <td><%= rec[k] %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody></table>
    <% end %>

    <% elsif sym == :dc %>

    <h2>DublinCore</h2>

    <%= form_tag(:controller => "application", :action => "download") do %>
      <input type='hidden' name='profile' value='dc'>
      <input type='hidden' name='user' value='<%= current_user %>'>
      <input type='hidden' name='filename' value='dc_ALL_<%= Time.now.strftime('%F_%H.%M.%S') %>'>
      <%= submit_tag("Download all DublinCore records") %>
    <% end %>

    <% @objects[:archive][:dc].each_value do |job| %>
      <%= form_tag(:controller => "application", :action => "download") do %>
        <% time = Time.at(job.first["job_id"].sub(/.*_([0-9]*)/, '\1').to_i) %>

        <input type='hidden' name='profile' value='dc'>
        <input type='hidden' name='job_id' value='<%= job.first['job_id'] %>'>
        <input type='hidden' name='filename' value='dc_<%= time.strftime('%F_%H.%M.%S') %>'>
        <h3>Job: <%= time.strftime('%F at %R') %></h3>
        <%= submit_tag("Download this job") %>
      <% end %>

      <table class='minted'><thead><tr>
        <th></th><th>Title</th><th>Creator</th>
        <th>Type</th><th>Date</th><th>Publisher</th>
        <th>Location</th><th>ARK</th>

        <% job.first.keys.reject { |k| ::ApplicationHelper.standard_header? k }.each do |k| %>
          <th><%= k %></th>
        <% end %>

      </tr></thead>
      <tbody>

        <% job.sort_by { |r| r["ark"] }.each do |rec| %>
          <tr>
            <td class='line_number'></td>
            <td><%= rec["dc_title"] %></td>
            <td><%= rec["dc_creator"] %></td>
            <td><%= rec["dc_type"] %></td>
            <td><%= rec["dc_date"] %></td>
            <td><%= rec["dc_publisher"] %></td>

            <% if !rec["target"].nil? && rec["target"].start_with?("http") %>
              <td><a href="<%= rec["target"] %>"><%= rec["target"] %></a></td>
            <% else %>
              <td><%= rec["target"] %></td>
            <% end %>

            <td><a href="http://ezid.cdlib.org/id/<%= rec["ark"] %>"><%= rec["ark"] %></a></td>

            <% rec.keys.reject { |k| ApplicationHelper.standard_header? k }.each do |k| %>
              <td><%= rec[k] %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody></table>
    <% end %>

  <% else %>
    <h2>Profile: ERC</h2>

    <%= form_tag(:controller => "application", :action => "download") do %>
      <input type='hidden' name='profile' value='erc'>
      <input type='hidden' name='user' value='<%= current_user %>'>
      <input type='hidden' name='filename' value='erc_ALL_<%= Time.now.strftime('%F_%H.%M.%S') %>'>
      <%= submit_tag("Download all ERC records") %>
    <% end %>

    <% @objects[:archive][:erc].each_value do |job| %>
      <%= form_tag(:controller => "application", :action => "download") do %>
        <% time = Time.at(job.first["job_id"].sub(/.*_([0-9]*)/, '\1').to_i) %>

        <input type='hidden' name='profile' value='erc'>
        <input type='hidden' name='job_id' value='<%= job.first['job_id'] %>'>
        <input type='hidden' name='filename' value='erc_<%= time.strftime('%F_%H.%M.%S') %>'>

        <h3>Job: <%= time.strftime('%F at %R') %></h3>
        <%= submit_tag("Download this job") %>
      <% end %>

      <table class='minted'><thead><tr>
        <th></th>
        <th>What</th><th>Who</th>
        <th>When</th><th>Location</th><th>ARK</th>

        <% job.first.keys.reject { |k| ApplicationHelper.standard_header? k }.each do |k| %>
          <th><%= k %></th>
        <% end %>

      </tr></thead>
      <tbody>

        <% job.sort_by { |r| r["ark"] }.each do |rec| %>
          <tr>
            <td class='line_number'></td>
            <td><%= rec["erc_what"] %></td>
            <td><%= rec["erc_who"] %></td>
            <td><%= rec["erc_when"] %></td>

            <% if !rec["target"].nil? && rec["target"].start_with?("http") %>
              <td><a href=\"<%= rec["target"] %>\"><%= rec["target"] %></a></td>
            <% else %>
              <td><%= rec["target"] %></td>
            <% end %>

            <td><a href="http://ezid.cdlib.org/id/<%= rec["ark"] %>"><%= rec["ark"] %></a></td>

            <% rec.keys.reject { |k| ApplicationHelper.standard_header? k }.each do |k| %>
              <td><%= rec[k] %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody></table>
    <% end %>
  <% end %>
<% end %>

app/views/application/create.html.erb
<header>
  <h1>Your ARKs are being processed!</h1>
</header>

<p>You’ll get an email when they’re ready.  Maybe <a href='<%= new_path %>' title='Mint ARKs'>mint some more</a> while you’re waiting?</p>

<p>(If it's a very small job it might be done already!  Check your
<%= link_to("archived jobs", archive_path) %>.)</p>

app/views/application/new.html.erb
<% if @profile.blank? %>
  <% return render "upload" %>
<% end %>

<header>
  <h1>Review objects (<a href='<%= new_path %>' title='Mint ARKs'>or start over</a>)</h1>
</header>

<%= form_tag({:controller => "application", :action => "create"}) do %>
  <input type='hidden' name='profile' value='<%= @profile %>'>

  <%
  proper = {
    :datacite => "DataCite",
    :dc => "DublinCore",
    :erc => "ERC",
  }
  %>

  <h2><%= proper[@profile] %> Objects</h2>

  <% if @status == :updates %>
    <h3>These records have already been minted</h3>
    <p>You may update their metadata now.  The metadata you see below
    is what you provided; make sure your metadata is not out-of-date!</p>
  <% else %>
    <h3>New records</h3>
  <% end %>

  <%= render partial: "table" %>

  <p>
    <label for='email'>We’ll email you when they’re ready:</label>
    <br>
    <input type='email' required name='email' placeholder='Enter your email address'>
  </p>

  <input type='hidden' name='user' value='<%= current_user %>'>
  <%= submit_tag("Finish") %>
<% end %>