config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#new"

  get "archive" => "application#archive"
  get "create" => "application#create"
  get "edit" => "application#edit"
  get "logout" => "sessions#destroy"
  get "new" => "application#new"
  post "create" => "application#create"
  post "download" => "application#download"
  post "login" => "sessions#create"
  post "new" => "application#new"
  post "update" => "application#update"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="<%= htmlclass(params) %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    <title><%= @title %> | UCSB EZID Minter</title>
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application" %>
  </head>
<body>

<% flash.each do |type, msg| %>
  <div class="<%= type %>">
    <p><%= msg %></p>
  </div>
<% end %>

<%= yield %>

<% if Rails.env.development? %>
  <% params[:session].delete :password if params[:session] %>
  <%= debug(params) %>
  </pre><code><%= @objects %></pre></code>
<% end %>

<footer>
  <p>Copyright &copy; 2016 The Regents of the University of California, All Rights Reserved.</p>
  <% if logged_in? %>
    <p class='logout'>Logged in as <%= current_user %></a>
      <ul>
        <li><a href='/archive' title='Archive of minted records'>Previously minted records</a></li>
        <li><%= link_to("Log out", logout_path) %></li>
      </ul>
    </p>
    <% end %>
</footer>
<%= javascript_include_tag("application", async: true, defer: true) %>

</body>
</html>